/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class contextquickie_windows_Translation */

#ifndef _Included_contextquickie_windows_Translation
#define _Included_contextquickie_windows_Translation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     contextquickie_windows_Translation
 * Method:    getTranslatedString
 * Signature: (Ljava/lang/String;JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_contextquickie_windows_Translation_getTranslatedString
  (JNIEnv *, jclass, jstring, jlong, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
