/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class contextquickie_tools_Registry_RootMapping */

#ifndef _Included_contextquickie_tools_Registry_RootMapping
#define _Included_contextquickie_tools_Registry_RootMapping
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
