/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class contextquickie_tools_Registry_HKEY */

#ifndef _Included_contextquickie_tools_Registry_HKEY
#define _Included_contextquickie_tools_Registry_HKEY
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
